### ISSUE TITLE
文件上传到自建minio服务失败

### ISSUE THREAD

**Issue by LinZhaoguan** [pig-mesh/oss-spring-boot-starter#6]
前提：minio服务通过nginx映射，minio的web管理页面可以正常访问。通过minio的web管理页面创建了一个bucket：test
步骤：1、引入本项目依赖，配置minio服务地址、秘钥等信息，配置bucket为test
           2、项目注入ossTemplate，调用上传文件方法 putObject

异常堆栈：
        `com.amazonaws.services.s3.model.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it. (Service: Amazon S3; Status Code: 409; Error Code: BucketAlreadyOwnedByYou; Request ID: 163FFBDBC1BF6CB8; S3 Extended Request ID: 01ae3220-608a-4188-83eb-7e50e266f2e7; Proxy: null)
, S3 Extended Request ID: 01ae3220-608a-4188-83eb-7e50e266f2e7
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1828)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1412)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1374)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5219)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5165)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:405)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6180)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1824)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1784)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1722)
	at com.pig4cloud.plugin.oss.service.OssTemplate.putObject(OssTemplate.java:214)
	at com.pig4cloud.plugin.oss.service.OssTemplate.putObject(OssTemplate.java:192)`

**Comment by lltx** [comment]
https://stackoverflow.com/questions/35356838/getting-error-bucketalreadyownedbyyou-your-previous-request-to-create-the-name
